### ISSUE TITLE
Option to specify multiple websites to process for management commands where appropriate

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#1135]
As a developer, I'd like to have the option of specifying multiple sites to process for these additional management commands:

 - [ ] `backpopulate_pipelines` (https://github.com/mitodl/ocw-studio/issues/1388)
 - [ ] `reset_sync_states`
 - [ ] `create_missing_gdrive_folders`
 - [ ] `sync_content_state`
 - [ ] `update_content_metadata`
 - [x] `import_ocw_course_sites` (completed as part of https://github.com/mitodl/ocw-studio/pull/1214)

**Comment by ChristopherChudzicki** [comment]
Would people still use `import_ocw_course_sites` to get sites for local dev?

To get prod/rc data I've been running `pg_dump RC_OR_PROD_DB` and then `pg_restore`ing my db from that, but that doesn't seem like the best way... (It's not bad, though, since our db is only a few hundred mb).

**Comment by mbertrand** [comment]
Yes, though I don't know if there's much demand for importing a large list of specific courses for local dev, I've always either imported all of them or individual ones.  Shouldn't be much work to add the option to it anyway.
