### ISSUE TITLE
overhaul pipeline management to use ol-concourse instead of raw yaml files

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#1872]
### Summary

Currently, `ocw-studio` supports building websites using the Concourse CI/CD system. There are a couple YAML pipeline definitions that accomplish this, `site-pipeline.yaml` for building an individual site and `mass-build-sites.yaml` for a single pipeline that builds all sites. There is also `theme-assets-pipeline.yaml` that pushes up a pipeline to build webpack assets that are re-usable by other site pipelines.

These pipelines need to be templated with various information that has grown more complex over time. At first, we just needed to fill in information such as git repo addresses and branches, the base URL for the site, API URLs, etc. Eventually to make the development experience better we added the ability to exclude or include whole sections of the pipeline definition in dev such as endpoint URLs for connecting to Minio, excluding Slack notification blocks, etc. This functionality has also been used to include or exclude portions of the definition based on it targeting the online build of the site visible on the web or the offline downloadable version of the site.

### The problem

Since the pipeline definitions are just YAML files, manipulating them inside a Python script amounts to nothing more than string manipulation. Dev and non-dev sections are fenced by comment blocks and stripped out or left in based on the current environment. Online / offline sections are fenced in the same way and stripped out or left in based on command line arguments. The YAML files themselves are massive and hard to read as there is a ton of repeated code. The whole system is brittle and making changes to it to accommodate conditions is problematic.

### The solution
The [`ol-concourse`](https://pypi.org/project/ol-concourse/) library is a Python library that can generate Concourse pipeline definitions using Pythonic code. Pipelines can be built using building blocks of reusable objects and the YAML generated on the fly. We should use this library to build our pipeline definitions dynamically instead of manually manipulating static YAML files with string manipulation. 

### Tasks (to be replaced with issues as created)
 - [x] https://github.com/mitodl/ocw-studio/issues/1895 - Extract common parts of the pipelines like error handling, webhooks and notifications into reusable components
 - [x] https://github.com/mitodl/ocw-studio/issues/1899 - Rebuild `theme-assets-pipeline.yml` as an `ol-concourse` Pipeline object
 - [x] https://github.com/mitodl/ocw-studio/issues/1905 - Rebuild `site-pipeline.yml` as an `ol-concourse` Pipeline object
 - [x] https://github.com/mitodl/ocw-studio/issues/1918 - Write a new mass build pipeline from scratch to replace `mass-build-sites.yaml` that instead of building all sites in a bash loop in a single task inside a single job in a single pipeline, re-purposes the new single site Pipeline object we created above to generate a new pipeline definition filled with batches of these that use the fan in / fan out [gated pipeline](https://concourse-ci.org/gated-pipeline-patterns.html) strategy
 - [x] https://github.com/mitodl/ocw-studio/issues/1927 - Rebuild `remove-unpublished-sites.yml` as an `ol-concourse` Pipeline object
 - [x] https://github.com/mitodl/ocw-studio/issues/1928 - Implement the above pipeline definitions in `content_sync/pipelines/concourse.py` so they are used with the management commands that push pipelines up to Concourse

**Comment by gumaerc** [comment]
This is complete and all pipeline definitions are now being generated using `ol-concourse` and being used in production
