### ISSUE TITLE
Epic: GitHub Sync Integration

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/ocw-studio#209]
RFC: https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit?usp=sharing

- [x] Create `ContentSyncState` [data model](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.w0avgftibuhn) (@rhysyngsun)
  - Migrate `WebsiteContent.hugo_filepath` to `ContentSyncState.content_filepath`
- [x] Create [Abstract Sync Backend](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.qe7jbq2m1mij) (@rhysyngsun)
- [x] Create [GitHub API wrapper](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.an0ws5n65p37) (@mbertrand)
- [x] Create sync backend for GitHub
- [x] Create [celery tasks](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.57df8kdcbsos)
  - [x] New `Website` -> new [github repo + branches](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.2232hzzes5x7)
  - [x] New `WebsiteContent`
  - [x] Update `WebsiteContent`
  - [x] Delete `WebsiteContent`
- [x] Add model signals to create/update `ContentSyncState` records and trigger appropriate celery tasks
- [x] Create [management command](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.92556rw1hgvz) to push all content to GitHub
- [ ] Create [management command](https://docs.google.com/document/d/1HCK1t-7L9poR4OHcL_tZuAeRB5VANSlQj5jXnsZTDA0/edit#heading=h.92556rw1hgvz) to pull all content from GitHub
- [x] [Create a github organization and user account with token to be used for creating/updating repos](https://github.com/mitodl/ocw-studio/issues/234) (@mitodl/devops)
- [x] [Assign github .env values for heroku deployments](https://github.com/mitodl/ocw-studio/issues/234)

**Comment by pdpinch** [comment]
I don't know if we have a management command to pull _all_ content from github, but I just used a command that pulled one course and it worked well (albeit slowly)
