### ISSUE TITLE
EPIC: OCW Studio MVP

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#38]
## Docs

[Google Docs folder](https://drive.google.com/drive/u/1/folders/1XC61Ool8hCTdkZPUR-foB6HFjkjSZkE8)
[Initial wireframes](https://lucid.app/lucidchart/6be33dd8-f7db-47f8-8af8-338255f23c3c/edit?shared=true&page=0_0#?folder_id=home&browser=icon)
[Updated page designs](https://xd.adobe.com/view/255b2552-3157-4c4f-9878-c40c314be5ff-7008/)

### Milestone 1: Users can author a complete site within the app

_Goal: Basic web app functionality is set up, and users can create all the content for a basic navigable site and have it saved in our database._

**Authoring UI & CRUD**
- [x] Basic site detail UI - https://github.com/mitodl/ocw-studio/issues/40
- [x] Site creation UI - https://github.com/mitodl/ocw-studio/issues/45
- [x] Implement page content UI and evaluate Netlify - https://github.com/mitodl/ocw-studio/issues/52
- [x] Implement page content listing UI - https://github.com/mitodl/ocw-studio/issues/56
- [x] Add collaborator screens - https://github.com/mitodl/ocw-studio/issues/60
- [x] Implement basic file upload - https://github.com/mitodl/ocw-studio/issues/92
- [x] Initial support for updated site config - https://github.com/mitodl/ocw-studio/issues/120
- [x] Add site listing page - https://github.com/mitodl/ocw-studio/issues/106
- [x] Add site navigation screen - https://github.com/mitodl/ocw-studio/issues/102
- [x] (TBD) Implement resource UI with file-specific metadata collection
- [x] (TBD) Implement remaining MVP input widgets
- [x] (TBD) Update styling to match [updated designs](https://xd.adobe.com/view/255b2552-3157-4c4f-9878-c40c314be5ff-7008/)
  - [x] First pass at styling - https://github.com/mitodl/ocw-studio/issues/115 
- [x] Add pagination for WebsiteContent API results - https://github.com/mitodl/ocw-studio/issues/96

**WYSIWYG Editor**
- [x] Evaluate CKEditor - https://github.com/mitodl/ocw-studio/issues/39
- [x] Add documentation for creating a new CKEditor plugin/widget
- [x] Add markdown plugin to CKEditor
- [x] Implement media embed widget (Youtube, Vimeo, etc.) (#99)
- [x] (TBD) Implement internal link widget (pages and resources)
- [x] (TBD) Implement image embed widget

**Other**
- [x] Support local site config - https://github.com/mitodl/ocw-studio/issues/37
- [x] Add permissions to existing viewsets - https://github.com/mitodl/ocw-studio/issues/63
- [x] Add auth library and implement Touchstone login - https://github.com/mitodl/ocw-studio/issues/62

-----

### Milestone 2: Site content can used to build files that Hugo can serve as a static site

_Goal: Our "pre-build" process is set up such that it can be run against an authored site in our database, and create a file structure that can be served as a fully-working static site by running "hugo server"_

Issues TBD

**Comment by pdpinch** [comment]
everything here is done
