### ISSUE TITLE
Video processing epic for OCW Studio

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ocw-studio#403]
As a user, I'd like to upload videos to a specific folder within a Google Drive, where they will be automatically streamed to S3,  transcoded, auto-captioned, uploaded to Youtube and Internet Archive, and added as resources to the appropriate Website.

#### Designs and Mockups
A service account will be created with access to the Google Drive folder.

Each subfolder should correspond to a website (preferably via its unique slug, though it is also possible to use a different convention, perhaps customizable via the `Website` or `WebsiteStarter` config). 

Whenever a file is changed or modified within this folder, a push notification will be sent to an API endpoint in OCW Studio.  For each new/modified file, its matching `Website` will be determined based on the parent folder.  A `WebsiteVideo` object will be created or retrieved in the database based on the video filename.
 Each `WebsiteVideo` object will have a `status` field that is regularly updated with each processing step ("Uploading to S3", "Transcoding", "Uploading to Youtube", etc).

If the video is determined to be new or modified, it will be uploaded to the OCW Studio S3 bucket and then sent to Elastic Transcoder for processing, similar to OVS.  The transcoding output format is TBD.  

**_Q_**: Should we use AWS Elemental MediaConvert instead of Elastic Transcoder (discussed in a zoom with Amazon last year)?  Supposedly faster and cheaper, but would require more original code instead of copying the OVS approach.

A separate recurring task will check for transcode job statuses, again similar to OVS (unless a notification can be sent to an OCW Studio endpoint instead).  Once a transcode is complete, one of the transcode outputs will be uploaded to Youtube (which account?).  Another (or the same) output format will be uploaded to Internet Archive.  

The transcode output also needs to be sent to an auto captioning service (more details necessary).

Yet another recurring task will check for Youtube upload results.  Once the Youtube upload is complete, the youtube id  for the video will be saved to the `WebsiteVideo.youtube_id` field, and a new `WebsiteContent` resource will be created for the video.  Instead of a file attachment, a video resource will have a youtube link.

#### Acceptance Criteria:

- [x] Set up syncing between a Google Drive folder and S3. https://github.com/mitodl/ocw-studio/issues/408
- [x] Transcoder pipeline for videos with correct output formats https://github.com/mitodl/ocw-studio/issues/470
- [ ] Transcoded videos are uploaded to Internet Archive
- [x] Transcoded videos are uploaded to Youtube https://github.com/mitodl/ocw-studio/issues/480
- [x] Transcoded videos are auto captioned
- [x] A `WebsiteContent` video resource is created for each video, with a link to the Youtube URL.

**Comment by pdpinch** [comment]
@mbertrand I think we can check some more of these boxes?
