### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-studio#569]
As a course author, I'd like to be able to create, edit and publish tables in my course

#### Acceptance Criteria:

- [x] Turn on the CKEditor tables widget & configure it to work with markdown
  - [x] does it handle escaping `|` characters? 
  - [x] how/does it handle colspan?
  - [x] how/does it handle line breaks?
- [x] export markdown for tables
- [x] make any necessary theme updates 
   - [x] desktop
   - [x] mobile 
- [x] allow course author to edit tables they created in studio
- [ ] allow course author to edit tables that were imported via ocw-to-hugo 
- [x] #663
- [x] #672
- [x] #673

**Comment by pdpinch** [comment]
@alicewriteswrongs can you update this issue? Do you think we could close it yet?

**Comment by alicewriteswrongs** [comment]
the only thing I'm not sure about is editing imported tables (i.e. tables produced by `ocw-to-hugo` - @gumaerc do you know if `ocw-to-hugo` has been updated / if that's supported yet?

**Comment by pdpinch** [comment]
Editing imported tables on RC is working fine for me. I'm closing this epic.
