### ISSUE TITLE
import course metadata

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-studio#579]
Currently, only instructors are being imported into the course metadata when running `import_ocw_course_sites`.  This process should also import:

 - [ ] `course_title`
 - [ ] `course_description`
 - [ ] `course_image`, `course_image-thumbnail` -> resources
 - [ ] `departments` -> `department_numbers`
 - [ ] `course_features` -> `course_feature_tags`
 - [ ] `topics`
 - [ ] `primary_course_number`
 - [ ] `extra_course_numbers`
 - [ ] `level`
 - [ ] `term` ?
 - [ ] various "other versions"
